---
title: "Network Status"
description: |
  A short description of the post.
author:
  - name: Abhijit Mahishi
    url: {}
date: 2022-05-11
output:
  distill::distill_article:
    self_contained: false
draft: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(igraph)
library(stringr)
library(tidyverse)
```

Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.

```{r}
temp<-centr_eigen(imf2014.ig,directed=T)
length(temp$vector)

head(power_centrality(imf2014.ig))

gotlike.nodes$bonpow<-power_centrality(gotlike.ig)
#arrange descending and return top 5 nodes
arrange(gotlike.nodes, desc(bonpow)) %>%
slice(1:5)
```
Derived 
```{r}
mat2014<-as.matrix(as_adjacency_matrix(imf2014.ig, attr="weight"))
imf2014.nodes$rc<-diag(mat2014sq)/rowSums(mat2014sq)
imf2014.nodes$rc<-ifelse(is.nan(imf2014.nodes$rc),0,imf2014.nodes$rc)
imf2014.nodes$eigen.rc<-imf2014.nodes$eigen*imf2014.nodes$rc

#Calculate the proportion of derived centrality.
imf2014.nodes$dc<-1-diag(mat2014sq)/rowSums(mat2014sq)
#replace missing values with 0
imf2014.nodes$dc<-ifelse(is.nan(imf2014.nodes$dc),1,imf2014.nodes$dc)
#Calculate received eigenvalue centrality
imf2014.nodes$eigen.dc<-imf2014.nodes$eigen*imf2014.nodes$dc
```
Plotting
```{r}
imf2014.nodes%>%
select(-name) %>%
gather() %>%
ggplot(aes(value)) +
geom_histogram() +
facet_wrap(~key, scales = "free")

## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.

```
Correlations
```{r}
temp<-imf2014.nodes %>%
select(totdegree,indegree,outdegree,eigen,eigen.rc,eigen.dc, starts_with("bon"))%>% correlate() %>% rearrange()
rplot(temp)
```

